name: request_ticket
description: A Request ticket Flutter mobile project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.4
  collection: any
  dio: ^5.0.3
  dots_indicator: ^3.0.0
  email_validator: '^2.1.16'
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.15
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.4
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  freezed_annotation: any
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_maps_flutter: ^2.2.6
  google_sign_in: ^6.0.2
  image_picker: ^0.8.7+5
  intl: any
  intl_utils: any
  json_annotation: any
  location: ^4.4.0
  pinput: ^2.2.31
  provider: ^6.0.5
  random_string: ^2.3.1
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  url_launcher: ^6.1.10
  uuid: ^3.0.7

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: ^0.12.0
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logo/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic

# ---- Config for package ----

flutter_icons:
  image_path: "assets/images/ic_travel_app.png"
  android: "launcher_icon"
  ios: true

flutter_native_splash:
  image: "assets/images/ic_travel_app.png"
  background_image: "assets/logo/splash_background.png"

flutter_intl:
  enabled: true
  class_name: L10n
  main_locale: vi
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  use_deferred_loading: false
