// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFm6Un1iQ6-_MgHchodBTeqCCxYxJYLWs',
    appId: '1:1075629088067:android:e9d7a04a6c2eeb24c6e3f6',
    messagingSenderId: '1075629088067',
    projectId: 'chat-researchteam',
    databaseURL: 'https://chat-researchteam-default-rtdb.firebaseio.com',
    storageBucket: 'chat-researchteam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAo2ioUYTlruqxP2JRiuHpbSGh03G2KXg',
    appId: '1:1075629088067:ios:66736113345cca15c6e3f6',
    messagingSenderId: '1075629088067',
    projectId: 'chat-researchteam',
    databaseURL: 'https://chat-researchteam-default-rtdb.firebaseio.com',
    storageBucket: 'chat-researchteam.appspot.com',
    androidClientId:
        '1075629088067-05ukuthhbt7t1mjitjdouipdglttnhbe.apps.googleusercontent.com',
    iosClientId:
        '1075629088067-7ve50grfprnabn4t72e8m44qg203v29d.apps.googleusercontent.com',
    iosBundleId: 'com.imt.ticket',
  );
}
